<style>
	h1, h2, h3,h4, figure, p {
		text-align: center;
		margin: 0 auto;
	}
	h1 {
		font-size: 1.8em;
		text-transform: uppercase;
		font-weight: 400;
		margin: 0 0 0.5em 0;
	}
	input {
		font-size: 1.8em;
		text-transform: uppercase;
		font-weight: 400;
		margin: 0 auto;
		width:60%;
	}
	button {
		text-transform: uppercase;
		margin: 0 auto;
		width:20%;
		font-size: 1.6em;
	}

	h2 {
		font-size: 1.8em;
		text-transform: uppercase;
		font-weight: 1400;
		margin: 0 0 0.5em 0;
		color: green;
	}
	h3 {
		font-size: 1.8em;
		font-weight: 1400;
		margin: 0 0 0.5em 0;
		color: blue;
	}
    h4 {
		font-size: 1.2em;
		font-weight: 600;
		margin: 0 0 0.5em 0;
	}
	figure {
		margin: 0 0 1em 0;
	}
	img {
		width: 100%;
		margin: 0 0 1em 0;
	}
	p {
		margin: 1em auto;
	}

	progress {
		display: block;
		width: 200px;
		height:40px;
		margin: 0 auto;
	}
   .neutral {
        color:black;
	}
	.bearish{
		color:red;
	}
	.bullish{
		color:green;
	}
    :global(.autocomplete-list-item){
        text-align:left!important;
    }

	/*.progress-div {
	    width: 200px;
	    height: 40px;
	    align-items: center;
	    text-align: center;
	    margin: 0 auto;
	}
	.progress-label{
	    position: absolute;
	    display: block;
	    margin: -32px 90px;
	}

	progress:before {
	  content: attr(data-label);
	  font-size: 1em;
	  text-align: center;
	  margin: 8px 75px;
	  position: absolute;
	  font-weight: 800;
	}
	*/

	@media (min-width: 480px) {
		h1 {
			font-size: 4em;
		}
	}
</style>

<script>
	import { tweened } from 'svelte/motion';
	import { cubicOut } from 'svelte/easing';
	import AutoComplete from "simple-svelte-autocomplete";
	const dsrandom = require('random-gif');

	//const tickers = ["AAL","AAL DOOM","AAL KELLY","AAL WSB","AAL VOLUME","AAL CALL","AAPL","AAPL DOOM","AAPL KELLY","AAPL WSB","AAPL VOLUME","AAPL CALL","ALXN","ALXN DOOM","ALXN KELLY","ALXN WSB","ALXN VOLUME","ALXN CALL","AMC","AMC DOOM","AMC KELLY","AMC WSB","AMC VOLUME","AMC CALL","AMD","AMD DOOM","AMD KELLY","AMD WSB","AMD VOLUME","AMD CALL","AMZN","AMZN DOOM","AMZN KELLY","AMZN WSB","AMZN VOLUME","AMZN CALL","APHA","APHA DOOM","APHA KELLY","APHA WSB","APHA VOLUME","APHA CALL","ARKF","ARKF DOOM","ARKF KELLY","ARKF WSB","ARKF VOLUME","ARKF CALL","ARKK","ARKK DOOM","ARKK KELLY","ARKK WSB","ARKK VOLUME","ARKK CALL","BABA","BABA DOOM","BABA KELLY","BABA WSB","BABA VOLUME","BABA CALL","BAC","BAC DOOM","BAC KELLY","BAC WSB","BAC VOLUME","BAC CALL","BB","BB DOOM","BB KELLY","BB WSB","BB VOLUME","BB CALL","BKNG","BKNG DOOM","BKNG KELLY","BKNG WSB","BKNG VOLUME","BKNG CALL","BRK/B","BRK/B DOOM","BRK/B KELLY","BRK/B WSB","BRK/B VOLUME","BRK/B CALL","C","C DOOM","C KELLY","C WSB","C VOLUME","C CALL","CCIV","CCIV DOOM","CCIV KELLY","CCIV WSB","CCIV VOLUME","CCIV CALL","CCL","CCL DOOM","CCL KELLY","CCL WSB","CCL VOLUME","CCL CALL","CFO","CFO DOOM","CFO KELLY","CFO WSB","CFO VOLUME","CFO CALL","CHNG","CHNG DOOM","CHNG KELLY","CHNG WSB","CHNG VOLUME","CHNG CALL","CHTR","CHTR DOOM","CHTR KELLY","CHTR WSB","CHTR VOLUME","CHTR CALL","CRM","CRM DOOM","CRM KELLY","CRM WSB","CRM VOLUME","CRM CALL","CRSR","CRSR DOOM","CRSR KELLY","CRSR WSB","CRSR VOLUME","CRSR CALL","CVNA","CVNA DOOM","CVNA KELLY","CVNA WSB","CVNA VOLUME","CVNA CALL","CZR","CZR DOOM","CZR KELLY","CZR WSB","CZR VOLUME","CZR CALL","DIS","DIS DOOM","DIS KELLY","DIS WSB","DIS VOLUME","DIS CALL","DKNG","DKNG DOOM","DKNG KELLY","DKNG WSB","DKNG VOLUME","DKNG CALL","E","E DOOM","E KELLY","E WSB","E VOLUME","E CALL","EOD","EOD DOOM","EOD KELLY","EOD WSB","EOD VOLUME","EOD CALL","EV","EV DOOM","EV KELLY","EV WSB","EV VOLUME","EV CALL","EXPE","EXPE DOOM","EXPE KELLY","EXPE WSB","EXPE VOLUME","EXPE CALL","FB","FB DOOM","FB KELLY","FB WSB","FB VOLUME","FB CALL","FDX","FDX DOOM","FDX KELLY","FDX WSB","FDX VOLUME","FDX CALL","FE","FE DOOM","FE KELLY","FE WSB","FE VOLUME","FE CALL","FIS","FIS DOOM","FIS KELLY","FIS WSB","FIS VOLUME","FIS CALL","FISV","FISV DOOM","FISV KELLY","FISV WSB","FISV VOLUME","FISV CALL","GDDY","GDDY DOOM","GDDY KELLY","GDDY WSB","GDDY VOLUME","GDDY CALL","GE","GE DOOM","GE KELLY","GE WSB","GE VOLUME","GE CALL","GME","GME DOOM","GME KELLY","GME WSB","GME VOLUME","GME CALL","GOOGL","GOOGL DOOM","GOOGL KELLY","GOOGL WSB","GOOGL VOLUME","GOOGL CALL","GPN","GPN DOOM","GPN KELLY","GPN WSB","GPN VOLUME","GPN CALL","HCA","HCA DOOM","HCA KELLY","HCA WSB","HCA VOLUME","HCA CALL","IAC","IAC DOOM","IAC KELLY","IAC WSB","IAC VOLUME","IAC CALL","ICLN","ICLN DOOM","ICLN KELLY","ICLN WSB","ICLN VOLUME","ICLN CALL","IMO","IMO DOOM","IMO KELLY","IMO WSB","IMO VOLUME","IMO CALL","IPO","IPO DOOM","IPO KELLY","IPO WSB","IPO VOLUME","IPO CALL","JD","JD DOOM","JD KELLY","JD WSB","JD VOLUME","JD CALL","JPM","JPM DOOM","JPM KELLY","JPM WSB","JPM VOLUME","JPM CALL","LBRDK","LBRDK DOOM","LBRDK KELLY","LBRDK WSB","LBRDK VOLUME","LBRDK CALL","LSXMK","LSXMK DOOM","LSXMK KELLY","LSXMK WSB","LSXMK VOLUME","LSXMK CALL","MA","MA DOOM","MA KELLY","MA WSB","MA VOLUME","MA CALL","MELI","MELI DOOM","MELI KELLY","MELI WSB","MELI VOLUME","MELI CALL","MRO","MRO DOOM","MRO KELLY","MRO WSB","MRO VOLUME","MRO CALL","MSFT","MSFT DOOM","MSFT KELLY","MSFT WSB","MSFT VOLUME","MSFT CALL","MU","MU DOOM","MU KELLY","MU WSB","MU VOLUME","MU CALL","NFLX","NFLX DOOM","NFLX KELLY","NFLX WSB","NFLX VOLUME","NFLX CALL","NIO","NIO DOOM","NIO KELLY","NIO WSB","NIO VOLUME","NIO CALL","NOK","NOK DOOM","NOK KELLY","NOK WSB","NOK VOLUME","NOK CALL","NOW","NOW DOOM","NOW KELLY","NOW WSB","NOW VOLUME","NOW CALL","NVDA","NVDA DOOM","NVDA KELLY","NVDA WSB","NVDA VOLUME","NVDA CALL","NYC","NYC DOOM","NYC KELLY","NYC WSB","NYC VOLUME","NYC CALL","OSK","OSK DOOM","OSK KELLY","OSK WSB","OSK VOLUME","OSK CALL","PINS","PINS DOOM","PINS KELLY","PINS WSB","PINS VOLUME","PINS CALL","PLTR","PLTR DOOM","PLTR KELLY","PLTR WSB","PLTR VOLUME","PLTR CALL","PLUG","PLUG DOOM","PLUG KELLY","PLUG WSB","PLUG VOLUME","PLUG CALL","PT","PT DOOM","PT KELLY","PT WSB","PT VOLUME","PT CALL","PTON","PTON DOOM","PTON KELLY","PTON WSB","PTON VOLUME","PTON CALL","PYPL","PYPL DOOM","PYPL KELLY","PYPL WSB","PYPL VOLUME","PYPL CALL","QCOM","QCOM DOOM","QCOM KELLY","QCOM WSB","QCOM VOLUME","QCOM CALL","QQQ","QQQ DOOM","QQQ KELLY","QQQ WSB","QQQ VOLUME","QQQ CALL","R","R DOOM","R KELLY","R WSB","R VOLUME","R CALL","RIOT","RIOT DOOM","RIOT KELLY","RIOT WSB","RIOT VOLUME","RIOT CALL","RKT","RKT DOOM","RKT KELLY","RKT WSB","RKT VOLUME","RKT CALL","SE","SE DOOM","SE KELLY","SE WSB","SE VOLUME","SE CALL","SNAP","SNAP DOOM","SNAP KELLY","SNAP WSB","SNAP VOLUME","SNAP CALL","SNDL","SNDL DOOM","SNDL KELLY","SNDL WSB","SNDL VOLUME","SNDL CALL","SPY","SPY DOOM","SPY KELLY","SPY WSB","SPY VOLUME","SPY CALL","SQ","SQ DOOM","SQ KELLY","SQ WSB","SQ VOLUME","SQ CALL","TDG","TDG DOOM","TDG KELLY","TDG WSB","TDG VOLUME","TDG CALL","THCB","THCB DOOM","THCB KELLY","THCB WSB","THCB VOLUME","THCB CALL","TLRY","TLRY DOOM","TLRY KELLY","TLRY WSB","TLRY VOLUME","TLRY CALL","TMUS","TMUS DOOM","TMUS KELLY","TMUS WSB","TMUS VOLUME","TMUS CALL","TSLA","TSLA DOOM","TSLA KELLY","TSLA WSB","TSLA VOLUME","TSLA CALL","TWTR","TWTR DOOM","TWTR KELLY","TWTR WSB","TWTR VOLUME","TWTR CALL","UBER","UBER DOOM","UBER KELLY","UBER WSB","UBER VOLUME","UBER CALL","UPWK","UPWK DOOM","UPWK KELLY","UPWK WSB","UPWK VOLUME","UPWK CALL","UVXY","UVXY DOOM","UVXY KELLY","UVXY WSB","UVXY VOLUME","UVXY CALL","V","V DOOM","V KELLY","V WSB","V VOLUME","V CALL","VAR","VAR DOOM","VAR KELLY","VAR WSB","VAR VOLUME","VAR CALL","WFC","WFC DOOM","WFC KELLY","WFC WSB","WFC VOLUME","WFC CALL","WKHS","WKHS DOOM","WKHS KELLY","WKHS WSB","WKHS VOLUME","WKHS CALL"];
	const tickers = ["AAL","AAL DOOM", "AAL DIV","AAL KELLY","AAL WSB","AAL CALL","AAL VOLUME","AAPL","AAPL DOOM","AAPL DIV","AAPL KELLY","AAPL WSB","AAPL CALL","AAPL VOLUME","ABBV","ABBV DOOM","ABBV KELLY","ABBV WSB","ABBV CALL","ABBV VOLUME","ABT","ABT DOOM","ABT KELLY","ABT WSB","ABT CALL","ABT VOLUME","ADM","ADM DOOM","ADM KELLY","ADM WSB","ADM CALL","ADM VOLUME","ADP","ADP DOOM","ADP KELLY","ADP WSB","ADP CALL","ADP VOLUME","AFL","AFL DOOM","AFL KELLY","AFL WSB","AFL CALL","AFL VOLUME","ALB","ALB DOOM","ALB KELLY","ALB WSB","ALB CALL","ALB VOLUME","ALXN","ALXN DOOM","ALXN KELLY","ALXN WSB","ALXN CALL","ALXN VOLUME","AMC","AMC DOOM","AMC KELLY","AMC WSB","AMC CALL","AMC VOLUME","AMCR","AMCR DOOM","AMCR KELLY","AMCR WSB","AMCR CALL","AMCR VOLUME","AMD","AMD DOOM","AMD KELLY","AMD WSB","AMD CALL","AMD VOLUME","AMZN","AMZN DOOM","AMZN KELLY","AMZN WSB","AMZN CALL","AMZN VOLUME","AOS","AOS DOOM","AOS KELLY","AOS WSB","AOS CALL","AOS VOLUME","APD","APD DOOM","APD KELLY","APD WSB","APD CALL","APD VOLUME","APHA","APHA DOOM","APHA KELLY","APHA WSB","APHA CALL","APHA VOLUME","ARKF","ARKF DOOM","ARKF KELLY","ARKF WSB","ARKF CALL","ARKF VOLUME","ARKK","ARKK DOOM","ARKK KELLY","ARKK WSB","ARKK CALL","ARKK VOLUME","ATO","ATO DOOM","ATO KELLY","ATO WSB","ATO CALL","ATO VOLUME","BABA","BABA DOOM","BABA KELLY","BABA WSB","BABA CALL","BABA VOLUME","BAC","BAC DOOM","BAC KELLY","BAC WSB","BAC CALL","BAC VOLUME","BB","BB DOOM","BB KELLY","BB WSB","BB CALL","BB VOLUME","BDX","BDX DOOM","BDX KELLY","BDX WSB","BDX CALL","BDX VOLUME","BEN","BEN DOOM","BEN KELLY","BEN WSB","BEN CALL","BEN VOLUME","BF.B","BF.B DOOM","BF.B KELLY","BF.B WSB","BF.B CALL","BF.B VOLUME","BKNG","BKNG DOOM","BKNG KELLY","BKNG WSB","BKNG CALL","BKNG VOLUME","BRK/B","BRK/B DOOM","BRK/B KELLY","BRK/B WSB","BRK/B CALL","BRK/B VOLUME","C","C DOOM","C KELLY","C WSB","C CALL","C VOLUME","CAH","CAH DOOM","CAH KELLY","CAH WSB","CAH CALL","CAH VOLUME","CARR","CARR DOOM","CARR KELLY","CARR WSB","CARR CALL","CARR VOLUME","CAT","CAT DOOM","CAT KELLY","CAT WSB","CAT CALL","CAT VOLUME","CB","CB DOOM","CB KELLY","CB WSB","CB CALL","CB VOLUME","CCIV","CCIV DOOM","CCIV KELLY","CCIV WSB","CCIV CALL","CCIV VOLUME","CCL","CCL DOOM","CCL KELLY","CCL WSB","CCL CALL","CCL VOLUME","CFO","CFO DOOM","CFO KELLY","CFO WSB","CFO CALL","CFO VOLUME","CHNG","CHNG DOOM","CHNG KELLY","CHNG WSB","CHNG CALL","CHNG VOLUME","CHTR","CHTR DOOM","CHTR KELLY","CHTR WSB","CHTR CALL","CHTR VOLUME","CINF","CINF DOOM","CINF KELLY","CINF WSB","CINF CALL","CINF VOLUME","CL","CL DOOM","CL KELLY","CL WSB","CL CALL","CL VOLUME","CLX","CLX DOOM","CLX KELLY","CLX WSB","CLX CALL","CLX VOLUME","CRM","CRM DOOM","CRM KELLY","CRM WSB","CRM CALL","CRM VOLUME","CRSR","CRSR DOOM","CRSR KELLY","CRSR WSB","CRSR CALL","CRSR VOLUME","CTAS","CTAS DOOM","CTAS KELLY","CTAS WSB","CTAS CALL","CTAS VOLUME","CVNA","CVNA DOOM","CVNA KELLY","CVNA WSB","CVNA CALL","CVNA VOLUME","CVX","CVX DOOM","CVX KELLY","CVX WSB","CVX CALL","CVX VOLUME","CZR","CZR DOOM","CZR KELLY","CZR WSB","CZR CALL","CZR VOLUME","DIS","DIS DOOM","DIS KELLY","DIS WSB","DIS CALL","DIS VOLUME","DKNG","DKNG DOOM","DKNG KELLY","DKNG WSB","DKNG CALL","DKNG VOLUME","DOV","DOV DOOM","DOV KELLY","DOV WSB","DOV CALL","DOV VOLUME","E","E DOOM","E KELLY","E WSB","E CALL","E VOLUME","ECL","ECL DOOM","ECL KELLY","ECL WSB","ECL CALL","ECL VOLUME","ED","ED DOOM","ED KELLY","ED WSB","ED CALL","ED VOLUME","EMR","EMR DOOM","EMR KELLY","EMR WSB","EMR CALL","EMR VOLUME","EOD","EOD DOOM","EOD KELLY","EOD WSB","EOD CALL","EOD VOLUME","ESS","ESS DOOM","ESS KELLY","ESS WSB","ESS CALL","ESS VOLUME","EV","EV DOOM","EV KELLY","EV WSB","EV CALL","EV VOLUME","EXPD","EXPD DOOM","EXPD KELLY","EXPD WSB","EXPD CALL","EXPD VOLUME","EXPE","EXPE DOOM","EXPE KELLY","EXPE WSB","EXPE CALL","EXPE VOLUME","FB","FB DOOM","FB KELLY","FB WSB","FB CALL","FB VOLUME","FDX","FDX DOOM","FDX KELLY","FDX WSB","FDX CALL","FDX VOLUME","FE","FE DOOM","FE KELLY","FE WSB","FE CALL","FE VOLUME","FIS","FIS DOOM","FIS KELLY","FIS WSB","FIS CALL","FIS VOLUME","FISV","FISV DOOM","FISV KELLY","FISV WSB","FISV CALL","FISV VOLUME","FRT","FRT DOOM","FRT KELLY","FRT WSB","FRT CALL","FRT VOLUME","GD","GD DOOM","GD KELLY","GD WSB","GD CALL","GD VOLUME","GDDY","GDDY DOOM","GDDY KELLY","GDDY WSB","GDDY CALL","GDDY VOLUME","GE","GE DOOM","GE KELLY","GE WSB","GE CALL","GE VOLUME","GME","GME DOOM","GME KELLY","GME WSB","GME CALL","GME VOLUME","GOOGL","GOOGL DOOM","GOOGL KELLY","GOOGL WSB","GOOGL CALL","GOOGL VOLUME","GPC","GPC DOOM","GPC KELLY","GPC WSB","GPC CALL","GPC VOLUME","GPN","GPN DOOM","GPN KELLY","GPN WSB","GPN CALL","GPN VOLUME","GWW","GWW DOOM","GWW KELLY","GWW WSB","GWW CALL","GWW VOLUME","HCA","HCA DOOM","HCA KELLY","HCA WSB","HCA CALL","HCA VOLUME","HRL","HRL DOOM","HRL KELLY","HRL WSB","HRL CALL","HRL VOLUME","IAC","IAC DOOM","IAC KELLY","IAC WSB","IAC CALL","IAC VOLUME","ICLN","ICLN DOOM","ICLN KELLY","ICLN WSB","ICLN CALL","ICLN VOLUME","IMO","IMO DOOM","IMO KELLY","IMO WSB","IMO CALL","IMO VOLUME","IPO","IPO DOOM","IPO KELLY","IPO WSB","IPO CALL","IPO VOLUME","ITW","ITW DOOM","ITW KELLY","ITW WSB","ITW CALL","ITW VOLUME","JD","JD DOOM","JD KELLY","JD WSB","JD CALL","JD VOLUME","JNJ","JNJ DOOM","JNJ KELLY","JNJ WSB","JNJ CALL","JNJ VOLUME","JPM","JPM DOOM","JPM KELLY","JPM WSB","JPM CALL","JPM VOLUME","KMB","KMB DOOM","KMB KELLY","KMB WSB","KMB CALL","KMB VOLUME","KO","KO DOOM","KO KELLY","KO WSB","KO CALL","KO VOLUME","LBRDK","LBRDK DOOM","LBRDK KELLY","LBRDK WSB","LBRDK CALL","LBRDK VOLUME","LEG","LEG DOOM","LEG KELLY","LEG WSB","LEG CALL","LEG VOLUME","LIN","LIN DOOM","LIN KELLY","LIN WSB","LIN CALL","LIN VOLUME","LOW","LOW DOOM","LOW KELLY","LOW WSB","LOW CALL","LOW VOLUME","LSXMK","LSXMK DOOM","LSXMK KELLY","LSXMK WSB","LSXMK CALL","LSXMK VOLUME","MA","MA DOOM","MA KELLY","MA WSB","MA CALL","MA VOLUME","MCD","MCD DOOM","MCD KELLY","MCD WSB","MCD CALL","MCD VOLUME","MDT","MDT DOOM","MDT KELLY","MDT WSB","MDT CALL","MDT VOLUME","MELI","MELI DOOM","MELI KELLY","MELI WSB","MELI CALL","MELI VOLUME","MKC","MKC DOOM","MKC KELLY","MKC WSB","MKC CALL","MKC VOLUME","MMM","MMM DOOM","MMM KELLY","MMM WSB","MMM CALL","MMM VOLUME","MRO","MRO DOOM","MRO KELLY","MRO WSB","MRO CALL","MRO VOLUME","MSFT","MSFT DOOM","MSFT KELLY","MSFT WSB","MSFT CALL","MSFT VOLUME","MU","MU DOOM","MU KELLY","MU WSB","MU CALL","MU VOLUME","NFLX","NFLX DOOM","NFLX KELLY","NFLX WSB","NFLX CALL","NFLX VOLUME","NIO","NIO DOOM","NIO KELLY","NIO WSB","NIO CALL","NIO VOLUME","NOK","NOK DOOM","NOK KELLY","NOK WSB","NOK CALL","NOK VOLUME","NOW","NOW DOOM","NOW KELLY","NOW WSB","NOW CALL","NOW VOLUME","NUE","NUE DOOM","NUE KELLY","NUE WSB","NUE CALL","NUE VOLUME","NVDA","NVDA DOOM","NVDA KELLY","NVDA WSB","NVDA CALL","NVDA VOLUME","NYC","NYC DOOM","NYC KELLY","NYC WSB","NYC CALL","NYC VOLUME","O","O DOOM","O KELLY","O WSB","O CALL","O VOLUME","OSK","OSK DOOM","OSK KELLY","OSK WSB","OSK CALL","OSK VOLUME","OTIS","OTIS DOOM","OTIS KELLY","OTIS WSB","OTIS CALL","OTIS VOLUME","PBCT","PBCT DOOM","PBCT KELLY","PBCT WSB","PBCT CALL","PBCT VOLUME","PEP","PEP DOOM","PEP KELLY","PEP WSB","PEP CALL","PEP VOLUME","PG","PG DOOM","PG KELLY","PG WSB","PG CALL","PG VOLUME","PINS","PINS DOOM","PINS KELLY","PINS WSB","PINS CALL","PINS VOLUME","PLTR","PLTR DOOM","PLTR KELLY","PLTR WSB","PLTR CALL","PLTR VOLUME","PLUG","PLUG DOOM","PLUG KELLY","PLUG WSB","PLUG CALL","PLUG VOLUME","PNR","PNR DOOM","PNR KELLY","PNR WSB","PNR CALL","PNR VOLUME","PPG","PPG DOOM","PPG KELLY","PPG WSB","PPG CALL","PPG VOLUME","PT","PT DOOM","PT KELLY","PT WSB","PT CALL","PT VOLUME","PTON","PTON DOOM","PTON KELLY","PTON WSB","PTON CALL","PTON VOLUME","PYPL","PYPL DOOM","PYPL KELLY","PYPL WSB","PYPL CALL","PYPL VOLUME","QCOM","QCOM DOOM","QCOM KELLY","QCOM WSB","QCOM CALL","QCOM VOLUME","QQQ","QQQ DOOM","QQQ KELLY","QQQ WSB","QQQ CALL","QQQ VOLUME","R","R DOOM","R KELLY","R WSB","R CALL","R VOLUME","RIOT","RIOT DOOM","RIOT KELLY","RIOT WSB","RIOT CALL","RIOT VOLUME","RKT","RKT DOOM","RKT KELLY","RKT WSB","RKT CALL","RKT VOLUME","ROP","ROP DOOM","ROP KELLY","ROP WSB","ROP CALL","ROP VOLUME","RTN","RTN DOOM","RTN KELLY","RTN WSB","RTN CALL","RTN VOLUME","SE","SE DOOM","SE KELLY","SE WSB","SE CALL","SE VOLUME","SHW","SHW DOOM","SHW KELLY","SHW WSB","SHW CALL","SHW VOLUME","SNAP","SNAP DOOM","SNAP KELLY","SNAP WSB","SNAP CALL","SNAP VOLUME","SNDL","SNDL DOOM","SNDL KELLY","SNDL WSB","SNDL CALL","SNDL VOLUME","SPGI","SPGI DOOM","SPGI KELLY","SPGI WSB","SPGI CALL","SPGI VOLUME","SPY","SPY DOOM","SPY KELLY","SPY WSB","SPY CALL","SPY VOLUME","SQ","SQ DOOM","SQ KELLY","SQ WSB","SQ CALL","SQ VOLUME","SWK","SWK DOOM","SWK KELLY","SWK WSB","SWK CALL","SWK VOLUME","SYY","SYY DOOM","SYY KELLY","SYY WSB","SYY CALL","SYY VOLUME","T","T DOOM","T KELLY","T WSB","T CALL","T VOLUME","TDG","TDG DOOM","TDG KELLY","TDG WSB","TDG CALL","TDG VOLUME","TGT","TGT DOOM","TGT KELLY","TGT WSB","TGT CALL","TGT VOLUME","THCB","THCB DOOM","THCB KELLY","THCB WSB","THCB CALL","THCB VOLUME","Ticker","Ticker DOOM","Ticker KELLY","Ticker WSB","Ticker CALL","Ticker VOLUME","TLRY","TLRY DOOM","TLRY KELLY","TLRY WSB","TLRY CALL","TLRY VOLUME","TMUS","TMUS DOOM","TMUS KELLY","TMUS WSB","TMUS CALL","TMUS VOLUME","TROW","TROW DOOM","TROW KELLY","TROW WSB","TROW CALL","TROW VOLUME","TSLA","TSLA DOOM","TSLA KELLY","TSLA WSB","TSLA CALL","TSLA VOLUME","TWTR","TWTR DOOM","TWTR KELLY","TWTR WSB","TWTR CALL","TWTR VOLUME","UBER","UBER DOOM","UBER KELLY","UBER WSB","UBER CALL","UBER VOLUME","UPWK","UPWK DOOM","UPWK KELLY","UPWK WSB","UPWK CALL","UPWK VOLUME","UVXY","UVXY DOOM","UVXY KELLY","UVXY WSB","UVXY CALL","UVXY VOLUME","V","V DOOM","V KELLY","V WSB","V CALL","V VOLUME","VAR","VAR DOOM","VAR KELLY","VAR WSB","VAR CALL","VAR VOLUME","VFC","VFC DOOM","VFC KELLY","VFC WSB","VFC CALL","VFC VOLUME","WBA","WBA DOOM","WBA KELLY","WBA WSB","WBA CALL","WBA VOLUME","WFC","WFC DOOM","WFC KELLY","WFC WSB","WFC CALL","WFC VOLUME","WKHS","WKHS DOOM","WKHS KELLY","WKHS WSB","WKHS CALL","WKHS VOLUME","WMT","WMT DOOM","WMT KELLY","WMT WSB","WMT CALL","WMT VOLUME","XOM","XOM DOOM","XOM KELLY","XOM WSB","XOM CALL","XOM VOLUME"];
	let ticker = "AAL";

	const progress = tweened(0, {
		duration: 400,
		easing: cubicOut
	});


	let api_output = {"symbol":"welcome"};

	async function handleKeydown(event) {
		if (event.key === 'Enter') {
			//event.preventDefault();
			runAPI();
		}
		else {
			 return;
		}
	}
	function runAPI() {

			api_output = {"symbol":"waiting"};
			progress.set(0);
			fetch("./api/test?input_cmd="+ticker)
				.then(d => d.text())
				.then(d => (api_output = JSON.parse(d)));

	}
</script>


<div style='text-align: center; max-width:600px; margin: 0 auto;'>

        <AutoComplete class="my-ac"
		      bind:name="wysiwyg_ticker"
		      items={tickers} bind:selectedItem={ticker}
		      on:keydown={handleKeydown}
		      maxItemsToShowInList=7 hideArrow=true placeholder="AAL" showClear=true />

        <button on:click={runAPI}>
		GO
	</button>

</div>
    <br>

{#if api_output.symbol == "waiting"}
    <h3> Options data 🏋️ getting results ...</h3>
	<figure style='width:10%;margin:0 auto'>
	<img alt='Loading' src='loadcat.gif'>
</figure>
{:else if api_output.symbol == "welcome"}
    <h2>Type'n pick ☝️ </h2>
    <br>
    <p>How to?</p>
    <h2>👇</h2>

<figure style='width:80%;margin:0 auto'>
	<img alt='Fat Tony' src='FatNeoSPYHowTo-Fx.gif'>
	<figcaption>Fat Tony: I don't normally teach, but when I do, I do. 🎷</figcaption>
</figure>
{:else}
    <br>
    <h2 class="{api_output.main_class}">{api_output.main_point}</h2>
    <p>{@html api_output.description}</p>
    <h3>{api_output.supporting_data}</h3>
    <h4 class="{api_output.secondary_class}">{api_output.secondary_point}</h4>
    <p>{api_output.secondary_description}</p>
{/if}

 <!--
<figure>
	<img alt='Fat Tony' src='{dsrandom.randomGifHacker()}'>
	<figcaption>Fat Tony: I don't get testy. I get stabby.</figcaption>
</figure>
-->
<br>
<p><strong> Sign up for the <a href='https://oracled.mailchimpsites.com/'> 📯 DailySpread 📯</a></strong></p>
